server:
    port: 8090

config:
    oauth2:
        # openssl genrsa -out jwt.pem 2048
        # openssl rsa -in jwt.pem
        privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAv7Usy564M2S/qBRpwgUDCOVMQzFIB8ek2/YsYisY/PnCHPws
            Y/lETdSav3+OQ7o5/a8rWqTmUspK/wfaXbnEfG4RFSUaUvSRUzg6NpoO1uEi5AGK
            +nn+fX0idZd7azV2MPIKMWTd+VROYcOLBJIlHLk7gevKGBO4qeQDEcgRMGre0BZz
            hxnTZ4n/3rej8W847bTd78L0pP5noHwqKKnXS9ic0hL3zDvcSlyogyuSkwxNqGs8
            K2ZKQP8PFT652FOQUBmc6dQcd00hWjkTAtTgP7JdylG6DjHVSR5kMoP07AfI1IVz
            ENrZjdI7jLXKny2zJvL7bnEe807dpD7xilMmqwIDAQABAoIBAGo+HfU6oRraWtzr
            czDzVhs3+GvEhAbLvbGpXC+Lcu2//LPTjUZafmAj0x8NseoW6syMp5o0iPCY67cq
            wvnuWdYbqZvuVAhlQaS9JIXeGxs66fsyX7MwqLkjAFXq/ZsMpdO6T6vQGrRy5H2J
            wSFnXOnuPexioD13sH92vby9A8mweZG+8CQvB2pFPAS+6UhRsBjs26WsKiwownRB
            zeGwsknfGFz1qXtnDuF2VZ71O+uRCVq/7UmkkmS08IVJUuucUw4p0mDwlLpI+1wM
            T07d2sb07ik7zgBtfJorCzYJrVqW6l9bqaHHge4qZHD9Ww0stVQv0dGvKKv/1cTL
            zbbIsQECgYEA9rvtyDg2D8skJn8JpbNHpsMiPG207bkDtYakF5JjSh3/CifOmmxw
            2/vkPqnFpXNwUZJKEjAUZGuvJz3ApZZdftITlX/xu2f3IZrA0BrnPqNy+pjaaKCN
            Sf8ObODkjQfT/YwXrDW/24qwBfebMXEnuTJw4kweIc1yBwmoKB5Ozg8CgYEAxug6
            sy4w0hfpE0UZtR0IuVZZ32difzHEPCizSvM2ZYU9s5+RO2vbKxnhW31MBidpihms
            Ragw/s3RONrrTPLpOKoHJyPxVpulA8W7K3uSNx3UGiC0gQvJGq+Bmw+dWhpN7Egp
            JWEv8TqIQKq+fSMkaHf3yxU8P35xsHQCPnbpOaUCgYADOu6gAmxixIwSnPMpYjF7
            824NUHpf6l4sEDkxvc7i94WRQngn+Wd42dFhKKPXyK0dxEaH+m0p62b9oodVI6TR
            tjpfaK9nfrLzk60WjGOepFErCrlBSWjQITC1KDSVzBZwaVceAA4k96naSiWT/iFB
            AXIM5GY4lxH5GZ1D+TGa7QKBgQDCJGM/BsOyHJJrM5P++gLM26LG8mLqIUoXKeau
            LiuW9XEfBI09wW1faVhT8z0j+I4DtEE4kAyad4tSAiOOrL3Eh/iJVIS38x0iTHn+
            3BL/5wZiJi/okPdOK6XGEnyUOH58NIasrGqd+nKJI97fx1A/A3GB8A0pMCKJhwG1
            tFy53QKBgQCvsFLiE2IxUlVimp5LaS1IrbFlUd9gDd6qrjaAb7ftYhILRvgVDdEz
            X9Wrizh6WYTGzmw/3X0U3o9THJh1z6ceH/+qh5fsOA4UtdlkKdIUPAMTOLQ5EA6r
            C8ymxxdVw+/izmAMy3VI+GCXGOrwQ6mMWP+o9fFxMc/kpjnLFDHiyQ==
            -----END RSA PRIVATE KEY-----
        # openssl rsa -in jwt.pem -pubout
        publicKey: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv7Usy564M2S/qBRpwgUD
            COVMQzFIB8ek2/YsYisY/PnCHPwsY/lETdSav3+OQ7o5/a8rWqTmUspK/wfaXbnE
            fG4RFSUaUvSRUzg6NpoO1uEi5AGK+nn+fX0idZd7azV2MPIKMWTd+VROYcOLBJIl
            HLk7gevKGBO4qeQDEcgRMGre0BZzhxnTZ4n/3rej8W847bTd78L0pP5noHwqKKnX
            S9ic0hL3zDvcSlyogyuSkwxNqGs8K2ZKQP8PFT652FOQUBmc6dQcd00hWjkTAtTg
            P7JdylG6DjHVSR5kMoP07AfI1IVzENrZjdI7jLXKny2zJvL7bnEe807dpD7xilMm
            qwIDAQAB
            -----END PUBLIC KEY-----

